name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15

    - name: Build
      run: go build -v go/nm.go
      
    - name: Upload
      uses: actions/upload-artifact@main
      if: (!cancelled())
      with:
        name: nm
        path: .
